### ISSUE TITLE
Resulting file for combineTPGBT has entries where VMM, MMFE8, etc are 0

### ISSUE THREAD

**Issue by annmwang** [crogan/MMFE8_DataFormats#17]
There are extraneous entries -can these be removed? They cause the octuplet analysis code to segfault :( @jrfarah 
Thanks!

**Comment by jrfarah** [comment]
@sezata Hey Ann, I'm looking into this now. Are you sure the values for the MMFE8s within the extraneous entries are also 0? combineTPGBT checks to see if a board number does not register a hit and fills it with zeros, which I think would cause the behavior you described, but it fills in the MMFE8 value with the corresponding board IP. You can see it here at this for loop in the code: https://github.com/crogan/MMFE8_DataFormats/blob/master/src/combineTPGBT.C#L261

If you are referring to the code I just described, I think thats important so that the GBT data matches up with the TPfit data. 
 
If I'm talking about something completely different, let me know and I can provide an easy fix, just check the combined output before switching entries and if everything is 0 wipe the entry, no problem.

**Comment by annmwang** [comment]
<img width="922" alt="screen shot 2017-07-07 at 4 33 46 pm" src="https://user-images.githubusercontent.com/4992913/27975909-3fc9dbc4-6332-11e7-9163-e8978ddb2f9c.png">

**Comment by annmwang** [comment]
It seems that tpfit_MMFE8, tpfit_VMM, tpfit_CH are 0, but tpfit_BCID isn't?

**Comment by jrfarah** [comment]
@sezata yeah this is very weird. This seems to be happening most of the time, which means it isn't something I can just check and remove. Looking at the python ttree vs. the c ttree they are completely different. I will get back to you as soon as I have a solution. Sorry for any inconvenience this is causing

**Comment by jrfarah** [comment]
@sezata can you please add 

`if(i > 10000) {  break; }`

at or around line 249. for some reason this fixed the problem on my computer, i may have an idea why but it doesn't make sense. 

edit: just confirmed in TBrowser. It looks exactly like a Python file with a similar break. can you check to see if that temporarily solves the issue? if it does I think I know what might be causing the problem.

**Comment by annmwang** [comment]
@jrfarah It didn't work for me, I still see the same issue.

**Comment by jrfarah** [comment]
@sezata hmmm thats unfortunate, thanks for checking.

**Comment by jrfarah** [comment]
@sezata the issue seems to be that combineTPGBT is literally writing incorrect values to the `ROOT` file. These are the first couple of values that combineTPGBT gets:

106
118
107
102
0
105
106
118
107
102
0


And this is what it should be seeing:

102
105
106
107
116
118
102
105
106
107
116
118
102
105
106
107

**Comment by jrfarah** [comment]
@sezata, fixed the issue, creating a pull request now

**Comment by jrfarah** [comment]
@sezata ping

shouldn't this be closed haha

**Comment by annmwang** [comment]
Yes haha
